### ISSUE TITLE
Support for x/y axis labels

### ISSUE THREAD

**Issue by kabouzeid** [SwiftUIExtensions/Charts#19]

**Comment by ay42** [comment]
Thank you for your feedback. I added this with #20 in Version 0.0.5
You can check out this examples in the \Examples folder.
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-05 at 16 03 46](https://user-images.githubusercontent.com/2933241/70284793-2c020400-177a-11ea-87e2-6ccb5b9e06f6.png)

**Comment by kabouzeid** [comment]
That was fast, thank you!
